-- MySQL Script generated by MySQL Workbench
-- Fri Feb 26 10:15:51 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`land`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`land` ;

CREATE TABLE IF NOT EXISTS `mydb`.`land` (
  `id` INT NOT NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `length` FLOAT NULL COMMENT '',
  `width` FLOAT NULL COMMENT '',
  `size` FLOAT NULL COMMENT '',
  `user_create` INT NULL COMMENT '',
  `address` VARCHAR(45) NULL COMMENT '',
  `place_code` CHAR(2) NULL COMMENT '',
  `latitude` DOUBLE NULL COMMENT '',
  `longitude` DOUBLE NULL COMMENT '',
  `state` INT NULL COMMENT '',
  `selection_type` INT NULL COMMENT '',
  `max_row` INT NULL COMMENT '',
  `max_fam_per_row` INT NULL COMMENT '',
  `max_clone_per_fam` INT NULL COMMENT '',
  `create_time` TIME(64) NULL COMMENT '',
  `update_time` TIME(64) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`send_clone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`send_clone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`send_clone` (
  `id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `send_from` CHAR(2) NULL COMMENT '',
  `send_to` CHAR(2) NULL COMMENT '',
  `user_sender` INT NULL COMMENT '',
  `state` INT NULL COMMENT '',
  `status` INT NULL COMMENT '',
  `create_time` TIME(64) NULL COMMENT '',
  `update_time` TIME(64) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`receive_clone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`receive_clone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`receive_clone` (
  `id` INT NOT NULL COMMENT '',
  `send_clone_id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `send_by` CHAR(2) NULL COMMENT '',
  `recieve_by` CHAR(2) NULL COMMENT '',
  `user_receive` INT NULL COMMENT '',
  `state` INT NULL COMMENT '',
  `status` INT NULL COMMENT '',
  `create_time` TIME(64) NULL COMMENT '',
  `update_time` TIME(64) NULL COMMENT '',
  PRIMARY KEY (`id`, `send_clone_id`)  COMMENT '',
  CONSTRAINT `fk_receive_clone_send_clone`
    FOREIGN KEY (`send_clone_id`)
    REFERENCES `mydb`.`send_clone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`plant`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`plant` ;

CREATE TABLE IF NOT EXISTS `mydb`.`plant` (
  `id` INT NOT NULL COMMENT '',
  `receive_clone_id` INT NOT NULL COMMENT '',
  `receive_clone_send_clone_id` INT NOT NULL COMMENT '',
  `land_id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `amount` INT NULL COMMENT '',
  `row_number` INT NULL COMMENT '',
  `order_in_row` INT NULL COMMENT '',
  `planted_by` INT NULL COMMENT '',
  `survive_amount` INT NULL COMMENT '',
  `create_time` TIME(64) NULL COMMENT '',
  `update_time` TIME(64) NULL COMMENT '',
  `state` INT NULL COMMENT '',
  `status` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_plant_receive_clone1`
    FOREIGN KEY (`receive_clone_id` , `receive_clone_send_clone_id`)
    REFERENCES `mydb`.`receive_clone` (`id` , `send_clone_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_plant_land1`
    FOREIGN KEY (`land_id`)
    REFERENCES `mydb`.`land` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`clone` ;

CREATE TABLE IF NOT EXISTS `mydb`.`clone` (
  `id` INT NOT NULL COMMENT '',
  `plant_id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `place` CHAR(2) NULL COMMENT '',
  `is_dead` INT NULL COMMENT '',
  `create_time` TIME(64) NULL COMMENT '',
  `update_time` TIME(64) NULL COMMENT '',
  `state` INT NULL COMMENT '',
  `status` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_clone_plant1`
    FOREIGN KEY (`plant_id`)
    REFERENCES `mydb`.`plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`first_selection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`first_selection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`first_selection` (
  `id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `pics` VARCHAR(45) NULL COMMENT '',
  `overview` VARCHAR(45) NULL COMMENT '',
  `brix` VARCHAR(45) NULL COMMENT '',
  `heigth` VARCHAR(45) NULL COMMENT '',
  `stalk_size` VARCHAR(45) NULL COMMENT '',
  `internode_length` VARCHAR(45) NULL COMMENT '',
  `stuff` VARCHAR(45) NULL COMMENT '',
  `internal_firmness` VARCHAR(45) NULL COMMENT '',
  `internal_systom` VARCHAR(45) NULL COMMENT '',
  `clump_char` VARCHAR(45) NULL COMMENT '',
  `clump_shape` VARCHAR(45) NULL COMMENT '',
  `internode_amount` VARCHAR(45) NULL COMMENT '',
  `leaf_sheath` VARCHAR(45) NULL COMMENT '',
  `state` VARCHAR(45) NOT NULL COMMENT '',
  `clone_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `clone_id`)  COMMENT '',
  CONSTRAINT `fk_first_selection_clone1`
    FOREIGN KEY (`clone_id`)
    REFERENCES `mydb`.`clone` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`second_selection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`second_selection` ;

CREATE TABLE IF NOT EXISTS `mydb`.`second_selection` (
  `id` INT NOT NULL COMMENT '',
  `plant_id` INT NOT NULL COMMENT '',
  `code` VARCHAR(45) NULL COMMENT '',
  `pics` VARCHAR(45) NULL COMMENT '',
  `overview` VARCHAR(45) NULL COMMENT '',
  `brix` VARCHAR(45) NULL COMMENT '',
  `height` VARCHAR(45) NULL COMMENT '',
  `stalk_size` VARCHAR(45) NULL COMMENT '',
  `internode_length` VARCHAR(45) NULL COMMENT '',
  `stuff` VARCHAR(45) NULL COMMENT '',
  `internal_firmness` VARCHAR(45) NULL COMMENT '',
  `stuff` VARCHAR(45) NULL COMMENT '',
  `internal_systom` VARCHAR(45) NULL COMMENT '',
  `clump_char` VARCHAR(45) NULL COMMENT '',
  `clump_shape` VARCHAR(45) NULL COMMENT '',
  `internode_amount` VARCHAR(45) NULL COMMENT '',
  `leaf_sheath` VARCHAR(45) NULL COMMENT '',
  `state` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_second_selection_plant1`
    FOREIGN KEY (`plant_id`)
    REFERENCES `mydb`.`plant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pictures`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pictures` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pictures` (
  `id` INT NULL COMMENT '',
  `file_path` VARCHAR(45) NULL COMMENT '',
  `pic_type` VARCHAR(45) NULL COMMENT '',
  CONSTRAINT `fk_pictures_first_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`first_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brix_1st`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brix_1st` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brix_1st` (
  `id` INT NULL COMMENT '',
  `brix` FLOAT NULL COMMENT '',
  CONSTRAINT `fk_brix_first_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`first_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`heigth_1st`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`heigth_1st` ;

CREATE TABLE IF NOT EXISTS `mydb`.`heigth_1st` (
  `id` INT NULL COMMENT '',
  `height` INT NULL COMMENT '',
  CONSTRAINT `fk_heigth_first_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`first_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stalk_size_1st`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stalk_size_1st` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stalk_size_1st` (
  `id` INT NULL COMMENT '',
  `stalk_size` FLOAT NULL COMMENT '',
  CONSTRAINT `fk_stalk_size_first_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`first_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`internode_length_1st`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`internode_length_1st` ;

CREATE TABLE IF NOT EXISTS `mydb`.`internode_length_1st` (
  `id` INT NULL COMMENT '',
  `internode_length` FLOAT NULL COMMENT '',
  CONSTRAINT `fk_internode_length_first_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`first_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brix_2nd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`brix_2nd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`brix_2nd` (
  `id` INT NULL COMMENT '',
  `brix` FLOAT NULL COMMENT '',
  CONSTRAINT `fk_brix_2nd_second_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`second_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`heigth_2nd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`heigth_2nd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`heigth_2nd` (
  `id` INT NULL COMMENT '',
  `height` INT NULL COMMENT '',
  CONSTRAINT `fk_heigth_2nd_second_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`second_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`stalk_size_2nd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`stalk_size_2nd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`stalk_size_2nd` (
  `id` INT NULL COMMENT '',
  `stalk_size` FLOAT NULL COMMENT '',
  CONSTRAINT `fk_stalk_size_2nd_second_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`second_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`internode_length_2nd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`internode_length_2nd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`internode_length_2nd` (
  `id` INT NULL COMMENT '',
  `internode_length` FLOAT NULL COMMENT '',
  CONSTRAINT `fk_internode_length_2nd_second_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`second_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pictures_2nd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pictures_2nd` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pictures_2nd` (
  `id` INT NULL COMMENT '',
  `file_path` VARCHAR(45) NULL COMMENT '',
  `pic_type` VARCHAR(45) NULL COMMENT '',
  CONSTRAINT `fk_pictures_2nd_second_selection1`
    FOREIGN KEY (`id`)
    REFERENCES `mydb`.`second_selection` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`activity` (
  `id` INT NOT NULL COMMENT '',
  `message` VARCHAR(45) NULL COMMENT '',
  `userid` INT NULL COMMENT '',
  `create_time` VARCHAR(45) NULL COMMENT '',
  `update_time` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`comment` (
  `id` INT NOT NULL COMMENT '',
  `message` VARCHAR(45) NULL COMMENT '',
  `userid` VARCHAR(45) NULL COMMENT '',
  `create_time` VARCHAR(45) NULL COMMENT '',
  `update_time` VARCHAR(45) NULL COMMENT '',
  `activity_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `activity_id`)  COMMENT '',
  CONSTRAINT `fk_comment_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mydb`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pictures_on_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pictures_on_activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pictures_on_activity` (
  `id` INT NOT NULL COMMENT '',
  `picture` VARCHAR(45) NULL COMMENT '',
  `create_time` VARCHAR(45) NULL COMMENT '',
  `update_time` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `userid` INT NULL COMMENT '',
  `message` VARCHAR(45) NULL COMMENT '',
  `activity_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`, `activity_id`)  COMMENT '',
  CONSTRAINT `fk_picture_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mydb`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like_on_activity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`like_on_activity` ;

CREATE TABLE IF NOT EXISTS `mydb`.`like_on_activity` (
  `id` INT NOT NULL COMMENT '',
  `userid` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `activity_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_like_activity1`
    FOREIGN KEY (`activity_id`)
    REFERENCES `mydb`.`activity` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pictures_on_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pictures_on_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pictures_on_comment` (
  `id` INT NOT NULL COMMENT '',
  `picture` VARCHAR(45) NULL COMMENT '',
  `create_time` VARCHAR(45) NULL COMMENT '',
  `update_time` VARCHAR(45) NULL COMMENT '',
  `status` VARCHAR(45) NULL COMMENT '',
  `userid` INT NULL COMMENT '',
  `message` VARCHAR(45) NULL COMMENT '',
  `activity_id` INT NOT NULL COMMENT '',
  `comment_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_pictures_comment_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `mydb`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`like_on_comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`like_on_comment` ;

CREATE TABLE IF NOT EXISTS `mydb`.`like_on_comment` (
  `id` INT NOT NULL COMMENT '',
  `userid` VARCHAR(45) NULL COMMENT '',
  `name` VARCHAR(45) NULL COMMENT '',
  `create_time` VARCHAR(45) NULL COMMENT '',
  `update_time` VARCHAR(45) NULL COMMENT '',
  `comment_id` INT NOT NULL COMMENT '',
  `comment_activity_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  CONSTRAINT `fk_like_comment_comment1`
    FOREIGN KEY (`comment_id` , `comment_activity_id`)
    REFERENCES `mydb`.`comment` (`id` , `activity_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`registdevice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`registdevice` ;

CREATE TABLE IF NOT EXISTS `mydb`.`registdevice` (
  `id` INT NOT NULL COMMENT '',
  `device_id` VARCHAR(45) NULL COMMENT '',
  `push_key` VARCHAR(45) NULL COMMENT '',
  `app_ver` VARCHAR(45) NULL COMMENT '',
  `user_id` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`subscribe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`subscribe` ;

CREATE TABLE IF NOT EXISTS `mydb`.`subscribe` (
  `id` INT NOT NULL COMMENT '',
  `id` INT NULL COMMENT '',
  `follower_id` INT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
